### ISSUE TITLE
Signal is aborted without a reason

### ISSUE THREAD

**Issue by novvaccaine** [unnoq/orpc#879]
### Environment

Environment
Node 22.16.0
Vite 7.0.6
ORPC 1.7.11

### Reproduction

https://github.com/novvaccaine/llmchat/blob/main/packages/www/src/query/conversation.ts

### Describe the bug

I am using orpc with tanstack start api routes. I keep seeing this error when I navigate between routes

```
AbortError: signal is aborted without reason
```

I am using orpc client with tanstack query

### Logs

```sh

```

**Comment by dinwwwh** [comment]
This is expected when react strict mode enabled - shouldn't happen in production, when you navigate the request will be abort by tanstack query.

**Comment by ghost** [comment]
I deployed the app and can see the same error in console. In dev environment, the page itself crashed, here that's not happening. Is that ok? :)

<img width="3200" height="2000" alt="Image" src="https://github.com/user-attachments/assets/b32e45b6-c0f5-4caf-b49f-fd33724f7063" />

**Comment by dinwwwh** [comment]
This still happen in production if navigate too fast -> abort sending requests. You should try/catch to prevent it log into console.

If you never abort requests, this error will never happen :)
